### ISSUE TITLE
One-line generation

### ISSUE THREAD

**Issue by garak** [crisu83/php-shortid#1]
I'm considering the use of this library to replace uuid, for the sake of brevity.
Anyway, I think that separation of creating and generating in two distinct statement is overkill. What about a one-line generator? Since most of times I generate a single id, it would be far more convenient

**Comment by cniska** [comment]
What do you propose? Here is a practical implementation where we use this library to generate domain identities in our applications: https://github.com/nordsoftware/lumen-core/blob/develop/src/Domain/Model/ObjectId.php#L39

**Comment by garak** [comment]
You should move logic (including parameters) to a Factory class, then just instantiate that class from ShortId class and call a static method

**Comment by garak** [comment]
Never mind.
I opted for writing a different (and better, of course) [library](https://github.com/PUGX/shortid-php)
