### ISSUE TITLE
What is the posibility for collision?

### ISSUE THREAD

**Issue by mtangoo** [crisu83/php-shortid#2]
If used as ID column what are rate of collision

**Comment by cniska** [comment]
We use this library in many projects for generating domain IDs to our entities. However, we do ensure uniqueness before assigning a new ID to avoid collision. 

To answer your question I would say that the chance for collision is not much larger than the one with UUID v4. We use [RandomLib](https://github.com/ircmaxell/RandomLib) to generate a "good" random string.

**Comment by mtangoo** [comment]
Thanks @crisu83
